### PR TITLE
Remove gnulib.

### PR DESCRIPTION
**Pull request by orbea**
Warning: This has only tested that it compiles, please review before considering merging!

This entirely removes gnulib from metalog, after this all that is required to build metalog is.
```
autoreconf -fi
./configure
make
```
@m-kress Would you be willing to test/review this?

### CODE REVIEW

**Comment by m-kress** [comment]
@orbea: Yes, I will definitelly test this! \o/
Thanks for this!

**Comment by orbea** [comment]
Thanks! Its been a while since I had metalog setup and I will need to relearn the configuration before I can effectively test it further...

**Comment by m-kress** [comment]
Works beautyfully! Even cross compiling for armv7hf creates working binaries. Thank you very much!

**Comment by m-kress** [comment]
Without gnulib dependency this logger will become more interesting for others again. I definitelly think, this should become a new release. Please consider adding yourself to the ./AUTHORS file. Afterwards eighter of us should contact hvisage and ask him to create a new release (including changelog).

**Pull request merged**
