### PR TITLE
Port to PCRE2

### PR DESCRIPTION
**Pull request by jovanlanik**
PCRE is no longer being maintained so I did some work porting metalog to PCRE2. There shoudn't be any change in behavior but distributions that package metalog would have to update the dependancies.
I have tested this with the sample config and my personal config and found no issue. This should be further tested and if any bugs appear, fixed.
I've also added myself to the AUTHORS file, I hope that's fine.

### CODE REVIEW

**Comment by m-kress** [comment]
Wow! Thank you! I'll look at it.

**Review by m-kress — CHANGES_REQUESTED** [review]
It seems as the variable "const char *errptr;" is not needed any longer. Could you please remove it? It appears in line 121 and 155 of metalog.c.

I cross compiled it for armv7hf and it seems to be working as expected!

**Comment by jovanlanik** [comment]
@m-kress Thank you for merging. Could you also push out a new release?

**Comment by m-kress** [comment]
Done. Thanks for your contribution! :-)

**Pull request merged**
